// flow-typed signature: fe9dd73b84049ba4427abba3f5f1d72e
// flow-typed version: <<STUB>>/@expo/samples_v2.1.1/flow_v0.97.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@expo/samples'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@expo/samples' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@expo/samples/ExpoConfigView' {
  declare module.exports: any;
}

declare module '@expo/samples/ExpoLinksView' {
  declare module.exports: any;
}

// Filename aliases
declare module '@expo/samples/ExpoConfigView.js' {
  declare module.exports: $Exports<'@expo/samples/ExpoConfigView'>;
}
declare module '@expo/samples/ExpoLinksView.js' {
  declare module.exports: $Exports<'@expo/samples/ExpoLinksView'>;
}
declare module '@expo/samples/index' {
  declare module.exports: $Exports<'@expo/samples'>;
}
declare module '@expo/samples/index.js' {
  declare module.exports: $Exports<'@expo/samples'>;
}
