/**
 * ./src/core/constants/state/types.js
 *
 * @flow
 */

export default {
  // app
  CONFIG_REQUEST: "CONFIG_REQUEST",
  LOADED_CONFIG: "LOADED_CONFIG",
  SKIPPED_LOGIN: "SKIPPED_LOGIN",
  LOGGED_OUT: "LOGGED_OUT",
  LOGGED_IN: "LOGGED_IN",

  // trivias
  TRIVIAS_REQUEST: "TRIVIAS_REQUEST",
  TRIVIAS_FETCHED: "TRIVIAS_FETCHED",

  // user
  USER_UPDATED: "USER_UPDATED",

  // nav
  OPENED_SIDENAV: "OPENED_SIDENAV",
  CHANGE_PAGE: "CHANGE_PAGE"
};
