/**
 * ./src/core/constants/state/types.js
 *
 * @flow
 */

export default {
  // app
  CONFIG_REQUEST: "CONFIG_REQUEST",
  LOADED_CONFIG: "LOADED_CONFIG",
  SKIPPED_LOGIN: "SKIPPED_LOGIN",
  LOGGED_OUT: "LOGGED_OUT",
  LOGGED_IN: "LOGGED_IN",

  // trivia
  TRIVIA_FETCHED: "TRIVIA_FETCHED",
  TRIVIA_FETCH: "TRIVIA_FETCH",
  RESET: "RESET",

  // user
  USER_UPDATED: "USER_UPDATED",

  // nav
  OPENED_SIDENAV: "OPENED_SIDENAV",
  CHANGE_PAGE: "CHANGE_PAGE"
};
